export const QUERY_KEYS = {
  dashboard: ["dashboard"] as const,
  portfolioOverview: ["portfolio-overview"] as const,
  portfolios: ["portfolios"] as const,
  accounts: ["accounts"] as const,
  accountPositions: (accountId: string) => ["account-positions", accountId] as const,
  transactions: (accountId: string) => ["transactions", accountId] as const,
  transactionsAll: ["transactions", "all"] as const,
  allTransactions: (year: number) => ["transactions", "all", year] as const,
  dividendByTicker: ["dividend-by-ticker"] as const,
  dividendSummary: ["dividend-summary"] as const,
  dividendPositions: ["dividend-positions"] as const,
  dcaAnalysis: ["dca-analysis"] as const,
  investDca: ["invest-dca"] as const,
  settings: ["settings"] as const,
  exchangeRate: ["exchange-rate"] as const,
  exchangeRateAlerts: ["exchange-rate-alerts"] as const,
  stockPriceAlerts: ["stock-price-alerts"] as const,
  rebalancingAlerts: ["rebalancing-alerts"] as const,
  rebalancingAlert: (portfolioId: string) => ["rebalancing-alert", portfolioId] as const,
  rebalancingHistory: ["rebalancing-history"] as const,
  taxSummary: (year: number) => ["tax-summary", year] as const,
  overseasPositionsTax: ["overseas-positions-tax"] as const,
  dartDisclosures: (days: number) => ["dart-disclosures", days] as const,
  allocationHistory: (months: number) => ["allocation-history", months] as const,
  alertHistory: ["alert-history"] as const,
  benchmark: (indices: string, months: number) => ["benchmark", indices, months] as const,
} as const;
