"""add_fee_and_alert_history

Revision ID: 072c1f0d9e47
Revises: ab1_add_ds_account_type_idx
Create Date: 2026-06-04 13:35:49.513314

"""

from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa

from alembic import op

revision: str = "072c1f0d9e47"
down_revision: str | None = "ab1_add_ds_account_type_idx"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "alert_history",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("alert_type", sa.String(length=20), nullable=False),
        sa.Column("message", sa.Text(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("idx_alert_history_user_created", "alert_history", ["user_id", "created_at"], unique=False)
    op.drop_index(op.f("idx_asset_snapshots_user_account_date"), table_name="asset_snapshots")
    op.create_index(
        "idx_asset_snapshots_user_account_date",
        "asset_snapshots",
        ["user_id", "account_id", "snapshot_date"],
        unique=False,
        postgresql_ops={"snapshot_date": "DESC"},
    )
    op.drop_index(op.f("idx_snapshots_account_date_desc"), table_name="asset_snapshots")
    op.create_index(
        "idx_snapshots_account_date_desc",
        "asset_snapshots",
        ["account_id", "snapshot_date"],
        unique=False,
        postgresql_ops={"snapshot_date": "DESC"},
    )
    op.add_column("transactions", sa.Column("fee", sa.Numeric(precision=18, scale=2), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("transactions", "fee")
    op.drop_index(
        "idx_snapshots_account_date_desc",
        table_name="asset_snapshots",
        postgresql_ops={"snapshot_date": "DESC"},
    )
    op.create_index(
        op.f("idx_snapshots_account_date_desc"),
        "asset_snapshots",
        ["account_id", sa.literal_column("snapshot_date DESC")],
        unique=False,
    )
    op.drop_index(
        "idx_asset_snapshots_user_account_date",
        table_name="asset_snapshots",
        postgresql_ops={"snapshot_date": "DESC"},
    )
    op.create_index(
        op.f("idx_asset_snapshots_user_account_date"),
        "asset_snapshots",
        ["user_id", "account_id", sa.literal_column("snapshot_date DESC")],
        unique=False,
    )
    op.drop_index("idx_alert_history_user_created", table_name="alert_history")
    op.drop_table("alert_history")
    # ### end Alembic commands ###
