"""add goal bond and cash ceiling settings

Revision ID: 17f4ddd81cae
Revises: 4f867b6a40e8
Create Date: 2026-08-05 17:53:13.512182

"""

from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa

from alembic import op

revision: str = "17f4ddd81cae"
down_revision: str | None = "4f867b6a40e8"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # 자동생성이 함께 감지한 무관한 인덱스 drift(다른 세션의 미적용 마이그레이션으로 추정)는
    # 이 리비전 스코프(신규 컬럼 2개)와 무관하므로 제외 — 원본은 이 파일의 git 히스토리 참고.
    op.add_column("user_settings", sa.Column("goal_bond_ceiling_pct", sa.Numeric(precision=5, scale=2), nullable=True))
    op.add_column("user_settings", sa.Column("goal_cash_ceiling_pct", sa.Numeric(precision=5, scale=2), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user_settings", "goal_cash_ceiling_pct")
    op.drop_column("user_settings", "goal_bond_ceiling_pct")
    # ### end Alembic commands ###
