"""add_monthly_deposit_amount

Revision ID: 1b815a243623
Revises: a1b2c3d4e5f6
Create Date: 2026-05-11 11:14:48.397961

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '1b815a243623'
down_revision: Union[str, None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_settings', sa.Column('monthly_deposit_amount', sa.Numeric(precision=18, scale=2), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_settings', 'monthly_deposit_amount')
    # ### end Alembic commands ###
