"""sync_model_indexes_with_db

Revision ID: 2142c5b6b44a
Revises: aa3_transaction_dividend_unique
Create Date: 2026-06-03 11:12:13.052885

"""

from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

revision: str = "2142c5b6b44a"
down_revision: str | None = "aa3_transaction_dividend_unique"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("idx_asset_snapshots_user_account_date"), table_name="asset_snapshots")
    op.create_index(
        "idx_asset_snapshots_user_account_date",
        "asset_snapshots",
        ["user_id", "account_id", "snapshot_date"],
        unique=False,
        postgresql_ops={"snapshot_date": "DESC"},
    )
    op.drop_index(op.f("idx_snapshots_account_date_desc"), table_name="asset_snapshots")
    op.create_index(
        "idx_snapshots_account_date_desc",
        "asset_snapshots",
        ["account_id", "snapshot_date"],
        unique=False,
        postgresql_ops={"snapshot_date": "DESC"},
    )
    op.alter_column(
        "positions",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=False,
        existing_server_default=sa.text("now()"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "positions",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
        existing_server_default=sa.text("now()"),
    )
    op.drop_index(
        "idx_snapshots_account_date_desc",
        table_name="asset_snapshots",
        postgresql_ops={"snapshot_date": "DESC"},
    )
    op.create_index(
        op.f("idx_snapshots_account_date_desc"),
        "asset_snapshots",
        ["account_id", sa.literal_column("snapshot_date DESC")],
        unique=False,
    )
    op.drop_index(
        "idx_asset_snapshots_user_account_date",
        table_name="asset_snapshots",
        postgresql_ops={"snapshot_date": "DESC"},
    )
    op.create_index(
        op.f("idx_asset_snapshots_user_account_date"),
        "asset_snapshots",
        ["user_id", "account_id", sa.literal_column("snapshot_date DESC")],
        unique=False,
    )
    # ### end Alembic commands ###
