"""add include_in_total to asset_accounts

Revision ID: 33a12f46ad9a
Revises: 079ac4b72233
Create Date: 2026-05-19 00:50:27.958420

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '33a12f46ad9a'
down_revision: Union[str, None] = '079ac4b72233'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('asset_accounts', sa.Column('include_in_total', sa.Boolean(), server_default='true', nullable=False))
    op.drop_index(op.f('idx_exchange_rate_alerts_user_active'), table_name='exchange_rate_alerts')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('idx_exchange_rate_alerts_user_active'), 'exchange_rate_alerts', ['user_id', 'is_active'], unique=False)
    op.drop_column('asset_accounts', 'include_in_total')
    # ### end Alembic commands ###
