"""add market to rebalancing_plan_legs

Revision ID: 7d18503a7f06
Revises: 84e57b6606a5
Create Date: 2026-07-23 00:00:05.972448

"""

from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa

from alembic import op

revision: str = "7d18503a7f06"
down_revision: str | None = "84e57b6606a5"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "rebalancing_plan_legs", sa.Column("market", sa.String(length=10), server_default="KR", nullable=False)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("rebalancing_plan_legs", "market")
    # ### end Alembic commands ###
