"""add_deposit_krw_to_asset_accounts

Revision ID: 8ce6a6662752
Revises: 005
Create Date: 2026-05-07 06:15:26.776414

"""

from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa

from alembic import op

revision: str = "8ce6a6662752"
down_revision: str | None = "005"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("asset_accounts", sa.Column("deposit_krw", sa.Numeric(precision=18, scale=2), nullable=True))
    op.alter_column(
        "user_settings",
        "ob_access_token",
        existing_type=sa.TEXT(),
        type_=sa.String(),
        existing_nullable=True,
    )
    op.alter_column(
        "user_settings",
        "ob_refresh_token",
        existing_type=sa.TEXT(),
        type_=sa.String(),
        existing_nullable=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "user_settings",
        "ob_refresh_token",
        existing_type=sa.String(),
        type_=sa.TEXT(),
        existing_nullable=True,
    )
    op.alter_column(
        "user_settings",
        "ob_access_token",
        existing_type=sa.String(),
        type_=sa.TEXT(),
        existing_nullable=True,
    )
    op.drop_column("asset_accounts", "deposit_krw")
    # ### end Alembic commands ###
