"""add_dart_api_key_to_user_settings

Revision ID: 9451f5d41bd5
Revises: 8ce6a6662752
Create Date: 2026-05-07 19:57:54.878158

"""

from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa

from alembic import op

revision: str = "9451f5d41bd5"
down_revision: str | None = "8ce6a6662752"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("user_settings", sa.Column("dart_api_key", sa.String(length=512), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user_settings", "dart_api_key")
    # ### end Alembic commands ###
