"""add indicator subscriptions

Revision ID: a64e36a53a40
Revises: ah1_account_target_portfolio
Create Date: 2026-06-12 10:17:08.276321

"""

from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa

from alembic import op

revision: str = "a64e36a53a40"
down_revision: str | None = "ah1_account_target_portfolio"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "indicator_subscriptions",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("indicator_code", sa.String(length=32), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "user_id", "indicator_code", name="uq_indicator_subscription_user_code"
        ),
    )
    op.create_index(
        "idx_indicator_subscriptions_user", "indicator_subscriptions", ["user_id"], unique=False
    )
    op.drop_index(op.f("ix_asset_accounts_target_portfolio_id"), table_name="asset_accounts")
    op.drop_index(op.f("idx_asset_snapshots_user_account_date"), table_name="asset_snapshots")
    op.create_index(
        "idx_asset_snapshots_user_account_date",
        "asset_snapshots",
        ["user_id", "account_id", "snapshot_date"],
        unique=False,
        postgresql_ops={"snapshot_date": "DESC"},
    )
    op.drop_index(op.f("idx_snapshots_account_date_desc"), table_name="asset_snapshots")
    op.create_index(
        "idx_snapshots_account_date_desc",
        "asset_snapshots",
        ["account_id", "snapshot_date"],
        unique=False,
        postgresql_ops={"snapshot_date": "DESC"},
    )
    op.drop_index(
        op.f("uq_positions_account_ticker_current"),
        table_name="positions",
        postgresql_where="(snapshot_id IS NULL)",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        op.f("uq_positions_account_ticker_current"),
        "positions",
        ["account_id", "ticker"],
        unique=True,
        postgresql_where="(snapshot_id IS NULL)",
    )
    op.drop_index(
        "idx_snapshots_account_date_desc",
        table_name="asset_snapshots",
        postgresql_ops={"snapshot_date": "DESC"},
    )
    op.create_index(
        op.f("idx_snapshots_account_date_desc"),
        "asset_snapshots",
        ["account_id", sa.literal_column("snapshot_date DESC")],
        unique=False,
    )
    op.drop_index(
        "idx_asset_snapshots_user_account_date",
        table_name="asset_snapshots",
        postgresql_ops={"snapshot_date": "DESC"},
    )
    op.create_index(
        op.f("idx_asset_snapshots_user_account_date"),
        "asset_snapshots",
        ["user_id", "account_id", sa.literal_column("snapshot_date DESC")],
        unique=False,
    )
    op.create_index(
        op.f("ix_asset_accounts_target_portfolio_id"),
        "asset_accounts",
        ["target_portfolio_id"],
        unique=False,
    )
    op.drop_index("idx_indicator_subscriptions_user", table_name="indicator_subscriptions")
    op.drop_table("indicator_subscriptions")
    # ### end Alembic commands ###
