"""expand_transaction_ticker_to_varchar50

Revision ID: b608c0089442
Revises: 9451f5d41bd5
Create Date: 2026-05-07 21:36:06.997867

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'b608c0089442'
down_revision: Union[str, None] = '9451f5d41bd5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('transactions', 'ticker',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=50),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('transactions', 'ticker',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True)
    # ### end Alembic commands ###
