KIS_REAL_BASE_URL = "https://openapi.koreainvestment.com:9443"
KIS_MOCK_BASE_URL = "https://openapivts.koreainvestment.com:29443"

# 국내주식 TR_ID
TR_DOMESTIC_BUY_REAL = "TTTC0802U"
TR_DOMESTIC_BUY_MOCK = "VTTC0802U"
TR_DOMESTIC_SELL_REAL = "TTTC0801U"
TR_DOMESTIC_SELL_MOCK = "VTTC0801U"
TR_DOMESTIC_ORDER_CONFIRM_REAL = "TTTC8001R"
TR_DOMESTIC_ORDER_CONFIRM_MOCK = "VTTC8001R"
TR_DOMESTIC_BALANCE_REAL = "TTTC8434R"
TR_DOMESTIC_BALANCE_MOCK = "VTTC8434R"
TR_DOMESTIC_INQUIRE_PSBL_ORDER_REAL = "TTTC8908R"
TR_DOMESTIC_INQUIRE_PSBL_ORDER_MOCK = "VTTC8908R"
TR_DOMESTIC_PRICE = "FHKST01010100"
TR_DOMESTIC_ETF_PRICE = "FHPET01010000"  # ETF/ETN 현재가 + 분배율

# 해외주식 TR_ID
TR_OVERSEAS_BUY_REAL = "TTTT1002U"
TR_OVERSEAS_BUY_MOCK = "VTTT1002U"
TR_OVERSEAS_SELL_REAL = "TTTT1006U"
TR_OVERSEAS_SELL_MOCK = "VTTT1006U"
TR_OVERSEAS_BALANCE_REAL = "TTTS3012R"
TR_OVERSEAS_BALANCE_MOCK = "VTTS3012R"
TR_OVERSEAS_PRICE = "HHDFS00000300"

# 해외 시장 코드
OVERSEAS_MARKET_CODES = {
    "NYSE": "NYSE",
    "NASDAQ": "NASD",
    "AMEX": "AMEX",
}

OVERSEAS_MARKETS = frozenset(OVERSEAS_MARKET_CODES.keys())  # {"NYSE", "NASDAQ", "AMEX"}

# 국내 시장 구분
DOMESTIC_MARKET_DIV = "J"  # 주식
DOMESTIC_MARKET_DIV_ETF = "E"  # ETF/ETN

REDIS_TOKEN_KEY = "kis_token:{user_id}:{mode}"  # nosec B105 — Redis 키 템플릿; mode: real | mock
